package ex09;

import java.util.Scanner;

public class MyEception {

	private static Scanner input;

	public static void main(String[] args) throws Num {
		input = new Scanner(System.in);
        System.out.println("请输入一个数字，如果是3或4是则抛出异常：");
        double num = input.nextDouble();
        if((int)num==3||(int)num==4) {
        	 throw new Num(num);
        }
        else
        	System.out.println("输入的数字为"+num+"无异常抛出！");
	}

}

    class Num extends Exception{
	      public Num(double num) {
	    	  super("\n当前的数值为"+(int)num+"已按要求抛出异常！");
	      }
}